// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FlowMaster")>]
[<assembly: AssemblyProductAttribute("FlowMaster")>]
[<assembly: AssemblyDescriptionAttribute("Workflow for Automation and Manual Process tracking")>]
[<assembly: AssemblyVersionAttribute("1.0.1")>]
[<assembly: AssemblyFileVersionAttribute("1.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FlowMaster"
    let [<Literal>] AssemblyProduct = "FlowMaster"
    let [<Literal>] AssemblyDescription = "Workflow for Automation and Manual Process tracking"
    let [<Literal>] AssemblyVersion = "1.0.1"
    let [<Literal>] AssemblyFileVersion = "1.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
